language: python
python:
  - "3.6"
  #- "3.7" 3.7 is not supported by travis: https://github.com/travis-ci/travis-ci/issues/9069
install:
  - pip install pipenv
  - pipenv install --dev
script: pipenv run make test

